namespace Torroid
{
    runtimeclass Downloads : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        Downloads(String fileName, String totalSize);
        String FileName;
        String Percentage;
        Double DPercentage;
        String Size;
        String Speed;
        String PauseResumeIcon;
        Boolean IsDownloading;
    }
}
