namespace Torroid
{
    runtimeclass Downloads : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        Downloads(String fileName, String totalSize);
        String FileName;
        String Percentage;
        Double DPercentage;
        String CurSize;
        String TotalSize;
        String Speed;
        
    }
}
