import "Downloads.idl";

namespace Torroid
{
    runtimeclass DownloadsViewModel
    {
        DownloadsViewModel();
        Downloads Downloads{ get; };

        Windows.Foundation.Collections.IObservableVector<Downloads> DownloadsOBVector{ get; };

        void startDownloadStatsUpdates();
        void stopDownloadStatsUpdates();
    }
}